# Sourced from ReubenUKGB/dowde-replay-parser (MIT licensed):
# https://codeberg.org/ReubenUKGB/dowde-replay-parser

MAP_ASSET_BASE_URL = (
    "https://codeberg.org/ReubenUKGB/dowde-replay-parser/media/branch/main/"
    "packages/assets/src/assets/"
)

MAP_DISPLAY_NAMES = {
    "2P_ABANDON_ALL_HOPE": 'Abandon All Hope',
    "2P_ABSOLUTE_ZERO": 'Absolute Zero',
    "2P_BATTLE_MARSHES": 'Battle Marshes',
    "2P_BLOODY_HELL": 'Bloody Hell',
    "2P_BLOOD_RIVER": 'Blood River',
    "2P_DEADMANS_CROSSING": "Deadman's Crossing",
    "2P_EDEMUS_GAMBLE": 'Edemus Gamble',
    "2P_EDEN": 'Eden',
    "2P_EMERALD_RIVER": 'Emerald River',
    "2P_EMPERORS_VALLEY": "Emperor's Valley",
    "2P_FACEOFF": 'Faceoff',
    "2P_FALLEN_CITY": 'Fallen City',
    "2P_FATA_MORGANA": 'Fata Morga',
    "2P_FEAR": 'Fear',
    "2P_FRAZIERS_DEMISE": "Frazier's Demise",
    "2P_FROSTBITE_RIVER": 'Frostbite River',
    "2P_HAINES_DEMISE": "Haines' Demise",
    "2P_HELLFIRE_CANYON": 'Hellfire Canyon',
    "2P_MEETING_OF_MINDS": 'Meeting of Minds',
    "2P_MOONBASE": 'Moonbase',
    "2P_OUTER_REACHES": 'Outer Reaches',
    "2P_QUESTS_TRIUMPH": "Quest's Triumph",
    "2P_RAILWAY": 'Railway',
    "2P_RIVERBED": 'Riverbed',
    "2P_SHRINE_OF_EXCELLION": 'Shrine of Excellion',
    "2P_TAINTED_PAIR": 'Tainted Pair',
    "2P_TAZINS_FOLLY": "Tazin's Folly",
    "2P_TITAN_FALL": "Titan's Fall",
    "2P_TRANQUILITYS_END": "Tranquility's End",
    "2P_VALLEY_OF_KHORNE": 'Valley of Khorne',
    "2P_VELVET_DURESS": 'Velvet Duress',
    "2P_VILE_REEF": 'Vile Reef',
    "2P_VOLATILE_GROUND": 'Volatile Ground',
    "2P_VORTEX_PLATEAU": 'Vortex Plateau',
    "3P_FORTRESS": 'Fortress',
    "4P_ARIEL_HIGHLANDS": 'Ariel Highlands',
    "4P_BIFFYS_PERIL": "Biffy's Peril",
    "4P_BROKEN_LANDS": 'Broken Lands',
    "4P_CAPE_OF_DESPAIR": 'Cape of Despair',
    "4P_DOOM_SPIRAL": 'Doom Spiral',
    "4P_DREAD_PEAK": 'Dread Peak',
    "4P_ERES_BADLANDS": 'Eres Badlands',
    "4P_FORGOTTEN_ISLES": 'Forgotten Isles',
    "4P_GORHAEL_CRATER": "Gor'Hael Crater",
    "4P_GURMUNS_PASS": "Gurmun's Pass",
    "4P_ICE_FLOW": 'Ice Flow',
    "4P_INTO_THE_BREACH": 'Into the Breach',
    "4P_JANUS_SAVANNAH": 'Janus Savannah',
    "4P_MARCONIA": 'Marconia',
    "4P_MOUNTAIN_TRAIL": 'Mountain Trail',
    "4P_MURAD_SWAMPLANDS": 'Murad Swamplands',
    "4P_PANREA_LOWLANDS": 'Panrea Lowlands',
    "4P_QUATRA": 'Quatra',
    "4P_ROKCLAW_FOOTHILLS": 'Rokclaw Foothills',
    "4P_SAINTS_SQUARE": "Saint's Square",
    "4P_SKERRIES": 'The Skerries',
    "4P_TAINTED_PLACE": 'Tainted Place',
    "4P_TAINTED_SOUL": 'Tainted Soul',
    "4P_TARTARUS_CENTER": 'Tartarus Center',
    "4P_TIBORAXX": 'Tiboraxx',
    "4P_TORRENTS": 'Torrents',
    "4P_VAN_DE_MAR_MOUNTAINS": 'Van de Mar Mountains',
    "4P_VOLCANIC_REACTION": 'Volcanic Reaction',
    "5P_ACERIA_FORESTS": 'Aceria Forests',
    "5P_EYE_OF_GORGON": 'The Eye of Gorgon',
    "5P_RED_JUNGLE": 'Red Jungle',
    "5P_TOTMACHERS_PRISON": "Totmacher's Prison",
    "5P_VYASASTAN": 'Vyasastan',
    "6P_AGAMAR_DESERT": 'Agamar Desert',
    "6P_ALVARUS": 'Alvarus',
    "6P_BLOODSHED_ALLEY": 'Bloodshed Alley',
    "6P_CONFRONTATION": 'Confrontation',
    "6P_CROSSROADS": 'Crossroads',
    "6P_CROZIUS_ARCANUM": 'Crozius Arcanum',
    "6P_DREAD_ALLEY": 'Dread Alley',
    "6P_FURY_ISLAND": 'Fury Island',
    "6P_HYPERION_PEAKS": 'Hyperion Peaks',
    "6P_IRRIDENE": 'Irridene',
    "6P_JUNGLE_WALLS": 'Jungle Walls',
    "6P_KASYR_LUTIEN": 'Kasyr Lutien',
    "6P_KAURAV_CITY": 'Kaurav City',
    "6P_MORTALIS": 'Mortalis',
    "6P_NIRRAEIN": 'Nirraein',
    "6P_ORESTAN_PLAINS": 'Orestan Plains',
    "6P_PARMENIAN_HEATH": 'Parmenian Heath',
    "6P_PARMENIE": 'Parmenie',
    "6P_PAVONIAN_HEARTLAND": 'Pavonian Heartland',
    "6P_PAVONIS": 'Pavonis',
    "6P_PAYNES_RETRIBUTION": "Payne's Retribution",
    "6P_PRINCIPIAN_BADLANDS": 'Principian Badlands',
    "6P_RHEAN_FLOODLANDS": 'Rhean Floodlands',
    "6P_SHAKUN_COAST": 'Shakun Coast',
    "6P_TEMPLE_CYRENE": 'Temple of Cyrene',
    "6P_TESTING_GROUNDS": 'Testing Grounds',
    "6P_THARGORUM": 'Thargorum',
    "6P_TRISTRAM_PLAINS": 'Tristram Plains',
    "6P_TRIVIAN_GROVES": 'Trivian Groves',
    "6P_VANDEAN_COAST": 'Vandean Coast',
    "6P_WESTERN_BARRENS": 'Western Barrens',
    "6pteam_streets_of_vogen": 'Streets of Vogen',
    "8P_BURIAL_GROUNDS": 'Burial Grounds',
    "8P_CERULEA": 'Cerulea',
    "8P_DATURIAS_PITS": 'Daturias Pits',
    "8P_DEMES_NORTHLANDS": 'Demes Northlands',
    "8P_DOOM_CHAMBER": 'Doom Chamber',
    "8P_FORBIDDEN_JUNGLE": 'Forbidden Jungle',
    "8P_JALAGANDA_LOWLANDS": 'Jalaganda Lowlands',
    "8P_KIER_HARRAD": 'Kier Harrad',
    "8P_LOST_HOPE": 'Lost Hope',
    "8P_MONSE": 'Monse',
    "8P_MORHOLT_RANGE": 'Morholt Range',
    "8P_MORRIAH_COAST": 'Morriah Coast',
    "8P_OASIS_OF_SHARR": 'Oasis of Sharr',
    "8P_PENAL_COLONY": 'Penal Colony',
    "8P_RHEAN_JUNGLE": 'Rhean Jungle',
    "8P_THURABIS_PLATEAU": "Thur'Abis Plateau",
}

MAP_IMAGE_FILES = {
    "2P_ABANDON_ALL_HOPE": '2p_abandon_all_hope_mm.webp',
    "2P_ABSOLUTE_ZERO": '2p_absolute_zero_mm.webp',
    "2P_BATTLE_MARSHES": '2p_battle_marshes_mm.webp',
    "2P_BLOODY_HELL": '2p_bloody hell_mm.webp',
    "2P_BLOOD_RIVER": '2p_blood_river_mm.webp',
    "2P_DEADMANS_CROSSING": '2p_deadmans_crossing_mm.webp',
    "2P_EDEMUS_GAMBLE": '2p_edemus_gamble_mm.webp',
    "2P_EDEN": '2p_eden_mm.webp',
    "2P_EMERALD_RIVER": '2p_emerald_river_mm.webp',
    "2P_EMPERORS_VALLEY": '2p_emperors_valley_mm.webp',
    "2P_FACEOFF": '2p_faceoff_mm.webp',
    "2P_FALLEN_CITY": '2p_fallen_city_mm.webp',
    "2P_FATA_MORGANA": '2p_fata_morgana_mm.webp',
    "2P_FEAR": '2p_fear_mm.webp',
    "2P_FRAZIERS_DEMISE": '2p_fraziersdemise_mm.webp',
    "2P_FROSTBITE_RIVER": '2p_frostbite_river_mm.webp',
    "2P_HAINES_DEMISE": '2p_haines_demise_mm.webp',
    "2P_HELLFIRE_CANYON": '2p_hellfire_canyon_mm.webp',
    "2P_MEETING_OF_MINDS": '2p_meeting_of_minds_mm.webp',
    "2P_MOONBASE": '2p_moonbase_mm.webp',
    "2P_OUTER_REACHES": '2p_outer_reaches_mm.webp',
    "2P_QUESTS_TRIUMPH": '2p_quests_triumph_mm.webp',
    "2P_RAILWAY": '2p_railway_mm.webp',
    "2P_RIVERBED": '2p_river_bed_mm.webp',
    "2P_SHRINE_OF_EXCELLION": '2p_shrine_of_excellion_mm.webp',
    "2P_TAINTED_PAIR": '2p_tainted_pair_mm.webp',
    "2P_TAZINS_FOLLY": '2p_tazins_folly_mm.webp',
    "2P_TITAN_FALL": '2p_titan_fall_mm.webp',
    "2P_TRANQUILITYS_END": '2p_tranquilitys_end_mm.webp',
    "2P_VALLEY_OF_KHORNE": '2p_valley_of_khorne_mm.webp',
    "2P_VELVET_DURESS": '2p_velvet_duress_mm.webp',
    "2P_VILE_REEF": '2p_vile_reef_mm.webp',
    "2P_VOLATILE_GROUND": '2p_volatile_ground_mm.webp',
    "2P_VORTEX_PLATEAU": '2p_vortex_plateau_mm.webp',
    "3P_FORTRESS": '3p_fortress_mm.webp',
    "4P_ARIEL_HIGHLANDS": '4p_ariel_highlands_mm.webp',
    "4P_BIFFYS_PERIL": '4p_biffys_peril_mm.webp',
    "4P_BROKEN_LANDS": '4p_broken_lands_mm.webp',
    "4P_CAPE_OF_DESPAIR": '4p_cape_of_despair_mm.webp',
    "4P_DOOM_SPIRAL": '4p_doom_spiral_mm.webp',
    "4P_DREAD_PEAK": '4p_dread_peak_mm.webp',
    "4P_ERES_BADLANDS": '4p_eres_badlands_mm.webp',
    "4P_FORGOTTEN_ISLES": '4p_forgotten_isles_mm.webp',
    "4P_GORHAEL_CRATER": '4p_gorhael_crater_mm.webp',
    "4P_GURMUNS_PASS": '4p_gurmuns_pass_mm.webp',
    "4P_ICE_FLOW": '4p_ice_flow_mm.webp',
    "4P_INTO_THE_BREACH": '4p_into_the_breach_mm.webp',
    "4P_JANUS_SAVANNAH": '4p_janus_savannah_mm.webp',
    "4P_MARCONIA": '4p_marconia_mm.webp',
    "4P_MOUNTAIN_TRAIL": '4p_mountain_trail_mm.webp',
    "4P_MURAD_SWAMPLANDS": '4p_murad_swamplands_mm.webp',
    "4P_PANREA_LOWLANDS": '4p_panrea_lowlands_mm.webp',
    "4P_QUATRA": '4p_quatra_mm.webp',
    "4P_ROKCLAW_FOOTHILLS": '4p_rokclaw_foothills_mm.webp',
    "4P_SAINTS_SQUARE": '4p_saints_square_mm.webp',
    "4P_SKERRIES": '4p_skerries_mm.webp',
    "4P_TAINTED_PLACE": '4p_tainted_place_mm.webp',
    "4P_TAINTED_SOUL": '4p_tainted_soul_mm.webp',
    "4P_TARTARUS_CENTER": '4p_tartarus_center_mm.webp',
    "4P_TIBORAXX": '4p_tiboraxx_mm.webp',
    "4P_TORRENTS": '4p_torrents_mm.webp',
    "4P_VAN_DE_MAR_MOUNTAINS": '4p_van_de_mar_mountains_mm.webp',
    "4P_VOLCANIC_REACTION": '4p_volcanic reaction_mm.webp',
    "5P_ACERIA_FORESTS": '5p_aceria_forests_mm.webp',
    "5P_EYE_OF_GORGON": '5p_eye_of_gorgon_mm.webp',
    "5P_RED_JUNGLE": '5p_red_jungle_mm.webp',
    "5P_TOTMACHERS_PRISON": '5p_totmachers_prison_mm.webp',
    "5P_VYASASTAN": '5p_vyasastan_mm.webp',
    "6P_AGAMAR_DESERT": '6p_agamar_desert_mm.webp',
    "6P_ALVARUS": '6p_alvarus_mm.webp',
    "6P_BLOODSHED_ALLEY": '6p_bloodshed_alley_mm.webp',
    "6P_CONFRONTATION": '6p_confrontation_mm.webp',
    "6P_CROSSROADS": '6p_crossroads_mm.webp',
    "6P_CROZIUS_ARCANUM": '6p_crozius_arcanum_mm.webp',
    "6P_DREAD_ALLEY": '6p_dread_alley_mm.webp',
    "6P_FURY_ISLAND": '6p_fury_island_mm.webp',
    "6P_HYPERION_PEAKS": '6p_hyperion_peaks_mm.webp',
    "6P_IRRIDENE": '6p_irridene_mm.webp',
    "6P_JUNGLE_WALLS": '6p_jungle_walls_mm.webp',
    "6P_KASYR_LUTIEN": '6p_kasyr_lutien_mm.webp',
    "6P_KAURAV_CITY": '6p_kaurav_city_mm.webp',
    "6P_MORTALIS": '6p_mortalis_mm.webp',
    "6P_NIRRAEIN": '6p_nirraein_mm.webp',
    "6P_ORESTAN_PLAINS": '6p_orestan_plains_mm.webp',
    "6P_PARMENIAN_HEATH": '6p_parmenian_heath_mm.webp',
    "6P_PARMENIE": '6p_parmenie_mm.webp',
    "6P_PAVONIAN_HEARTLAND": '6p_pavonian_heartland_mm.webp',
    "6P_PAVONIS": '6p_pavonis_mm.webp',
    "6P_PAYNES_RETRIBUTION": '6p_paynes_retribution_mm.webp',
    "6P_PRINCIPIAN_BADLANDS": '6p_principian_badlands_mm.webp',
    "6P_RHEAN_FLOODLANDS": '6p_rhean_floodlands_mm.webp',
    "6P_SHAKUN_COAST": '6p_shakun_coast_mm.webp',
    "6P_TEMPLE_CYRENE": '6p_temple_cyrene_mm.webp',
    "6P_TESTING_GROUNDS": '6p_testing_grounds_mm.webp',
    "6P_THARGORUM": '6p_thargorum_mm.webp',
    "6P_TRISTRAM_PLAINS": '6p_tristram_plains_mm.webp',
    "6P_TRIVIAN_GROVES": '6p_trivian_groves_mm.webp',
    "6P_VANDEAN_COAST": '6p_vandea_coast_mm.webp',
    "6P_WESTERN_BARRENS": '6p_western_barrens_mm.webp',
    "6pteam_streets_of_vogen": '6pteam_streets_of_vogen_mm.webp',
    "8P_BURIAL_GROUNDS": '8p_burial_grounds_mm.webp',
    "8P_CERULEA": '8p_cerulea_mm.webp',
    "8P_DATURIAS_PITS": '8p_daturias_pits_mm.webp',
    "8P_DEMES_NORTHLANDS": '8p_demes_northlands_mm.webp',
    "8P_DOOM_CHAMBER": '8p_doom_chamber_mm.webp',
    "8P_FORBIDDEN_JUNGLE": '8p_forbidden_jungle_mm.webp',
    "8P_JALAGANDA_LOWLANDS": '8p_jalaganda_lowlands_mm.webp',
    "8P_KIER_HARRAD": '8p_kier_harrad_mm.webp',
    "8P_LOST_HOPE": '8p_lost_hope_mm.webp',
    "8P_MONSE": '8p_monse_mm.webp',
    "8P_MORHOLT_RANGE": '8p_morholt_range_mm.webp',
    "8P_MORRIAH_COAST": '8p_morriah_coast_mm.webp',
    "8P_OASIS_OF_SHARR": '8p_oasis_of_sharr_mm.webp',
    "8P_PENAL_COLONY": '8p_penal_colony_mm.webp',
    "8P_RHEAN_JUNGLE": '8p_rhean_jungle_mm.webp',
    "8P_THURABIS_PLATEAU": '8p_thurabis_plateau_mm.webp',
}

